
# This file is used to configure the Supabase CLI

[migrations]
# Sets a custom migrations table name
migrations_table = 'supabase_migrations'

[tables."properties"]
primary_key = 'id'
schema_name = 'public'

[tables."profiles"]
primary_key = 'id'
schema_name = 'public'

[tables."bookings"]
primary_key = 'id'
schema_name = 'public'

[tables."favorites"]
primary_key = 'id'
schema_name = 'public'

[tables."property_images"]
primary_key = 'id'
schema_name = 'public'

[tables."reviews"]
primary_key = 'id'
schema_name = 'public'

[storage]
create_buckets = true

[storage.buckets."property_images"]
public = true

[storage.buckets."avatars"]
public = true

